# coding: utf-8

"""
    Dalet Metadata Analysis API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: cortexsupport@dalet.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metadataanalysis_client
from metadataanalysis_client.api.auth_api import AuthApi  # noqa: E501
from metadataanalysis_client.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = metadataanalysis_client.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_access_token(self):
        """Test case for get_access_token

        """
        pass


if __name__ == '__main__':
    unittest.main()
