# coding: utf-8

"""
    Dalet Metadata Analysis API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: cortexsupport@dalet.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import metadataanalysis_client
from metadataanalysis_client.models.knowledge_graph_search_response_items import KnowledgeGraphSearchResponseItems  # noqa: E501
from metadataanalysis_client.rest import ApiException

class TestKnowledgeGraphSearchResponseItems(unittest.TestCase):
    """KnowledgeGraphSearchResponseItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test KnowledgeGraphSearchResponseItems
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = metadataanalysis_client.models.knowledge_graph_search_response_items.KnowledgeGraphSearchResponseItems()  # noqa: E501
        if include_optional :
            return KnowledgeGraphSearchResponseItems(
                result_score = 1.337, 
                result = metadataanalysis_client.models.knowledge_graph.KnowledgeGraph(
                    mid = '0', 
                    name = '0', 
                    types = [
                        '0'
                        ], 
                    description = '0', 
                    detailed_description = metadataanalysis_client.models.knowledge_graph_detailed_description.KnowledgeGraph_detailedDescription(
                        article_body = '0', 
                        url = '0', 
                        license = '0', ), 
                    image = metadataanalysis_client.models.knowledge_graph_image.KnowledgeGraph_image(
                        url = '0', 
                        content_url = '0', ), 
                    url = '0', )
            )
        else :
            return KnowledgeGraphSearchResponseItems(
        )

    def testKnowledgeGraphSearchResponseItems(self):
        """Test KnowledgeGraphSearchResponseItems"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
