# coding: utf-8

"""
    Dalet Metadata Analysis API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: cortexsupport@dalet.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metadataanalysis_client
from metadataanalysis_client.api.metadata_analysis_api import MetadataAnalysisApi  # noqa: E501
from metadataanalysis_client.rest import ApiException


class TestMetadataAnalysisApi(unittest.TestCase):
    """MetadataAnalysisApi unit test stubs"""

    def setUp(self):
        self.api = metadataanalysis_client.api.metadata_analysis_api.MetadataAnalysisApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analyze(self):
        """Test case for analyze

        """
        pass

    def test_knowledge_graph_search(self):
        """Test case for knowledge_graph_search

        """
        pass

    def test_segment_text(self):
        """Test case for segment_text

        """
        pass

    def test_translate_captions(self):
        """Test case for translate_captions

        """
        pass

    def test_translate_text(self):
        """Test case for translate_text

        """
        pass


if __name__ == '__main__':
    unittest.main()
