# coding: utf-8

"""
    Dalet Metadata Analysis API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: cortexsupport@dalet.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from metadataanalysis_client.configuration import Configuration


class KnowledgeGraphDetailedDescription(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'article_body': 'str',
        'url': 'str',
        'license': 'str'
    }

    attribute_map = {
        'article_body': 'articleBody',
        'url': 'url',
        'license': 'license'
    }

    def __init__(self, article_body=None, url=None, license=None, local_vars_configuration=None):  # noqa: E501
        """KnowledgeGraphDetailedDescription - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._article_body = None
        self._url = None
        self._license = None
        self.discriminator = None

        if article_body is not None:
            self.article_body = article_body
        if url is not None:
            self.url = url
        if license is not None:
            self.license = license

    @property
    def article_body(self):
        """Gets the article_body of this KnowledgeGraphDetailedDescription.  # noqa: E501


        :return: The article_body of this KnowledgeGraphDetailedDescription.  # noqa: E501
        :rtype: str
        """
        return self._article_body

    @article_body.setter
    def article_body(self, article_body):
        """Sets the article_body of this KnowledgeGraphDetailedDescription.


        :param article_body: The article_body of this KnowledgeGraphDetailedDescription.  # noqa: E501
        :type: str
        """

        self._article_body = article_body

    @property
    def url(self):
        """Gets the url of this KnowledgeGraphDetailedDescription.  # noqa: E501


        :return: The url of this KnowledgeGraphDetailedDescription.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this KnowledgeGraphDetailedDescription.


        :param url: The url of this KnowledgeGraphDetailedDescription.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def license(self):
        """Gets the license of this KnowledgeGraphDetailedDescription.  # noqa: E501


        :return: The license of this KnowledgeGraphDetailedDescription.  # noqa: E501
        :rtype: str
        """
        return self._license

    @license.setter
    def license(self, license):
        """Sets the license of this KnowledgeGraphDetailedDescription.


        :param license: The license of this KnowledgeGraphDetailedDescription.  # noqa: E501
        :type: str
        """

        self._license = license

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KnowledgeGraphDetailedDescription):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KnowledgeGraphDetailedDescription):
            return True

        return self.to_dict() != other.to_dict()
