# coding: utf-8

"""
    Dalet Metadata Analysis API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: cortexsupport@dalet.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from metadataanalysis_client.configuration import Configuration


class SegmentTextResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'dptt_file': 'Locator',
        'draftjs_file': 'Locator'
    }

    attribute_map = {
        'dptt_file': 'dpttFile',
        'draftjs_file': 'draftjsFile'
    }

    def __init__(self, dptt_file=None, draftjs_file=None, local_vars_configuration=None):  # noqa: E501
        """SegmentTextResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._dptt_file = None
        self._draftjs_file = None
        self.discriminator = None

        self.dptt_file = dptt_file
        self.draftjs_file = draftjs_file

    @property
    def dptt_file(self):
        """Gets the dptt_file of this SegmentTextResponse.  # noqa: E501


        :return: The dptt_file of this SegmentTextResponse.  # noqa: E501
        :rtype: Locator
        """
        return self._dptt_file

    @dptt_file.setter
    def dptt_file(self, dptt_file):
        """Sets the dptt_file of this SegmentTextResponse.


        :param dptt_file: The dptt_file of this SegmentTextResponse.  # noqa: E501
        :type: Locator
        """
        if self.local_vars_configuration.client_side_validation and dptt_file is None:  # noqa: E501
            raise ValueError("Invalid value for `dptt_file`, must not be `None`")  # noqa: E501

        self._dptt_file = dptt_file

    @property
    def draftjs_file(self):
        """Gets the draftjs_file of this SegmentTextResponse.  # noqa: E501


        :return: The draftjs_file of this SegmentTextResponse.  # noqa: E501
        :rtype: Locator
        """
        return self._draftjs_file

    @draftjs_file.setter
    def draftjs_file(self, draftjs_file):
        """Sets the draftjs_file of this SegmentTextResponse.


        :param draftjs_file: The draftjs_file of this SegmentTextResponse.  # noqa: E501
        :type: Locator
        """
        if self.local_vars_configuration.client_side_validation and draftjs_file is None:  # noqa: E501
            raise ValueError("Invalid value for `draftjs_file`, must not be `None`")  # noqa: E501

        self._draftjs_file = draftjs_file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SegmentTextResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SegmentTextResponse):
            return True

        return self.to_dict() != other.to_dict()
