# coding: utf-8

"""
    Dalet Metadata Analysis API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: cortexsupport@dalet.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from metadataanalysis_client.configuration import Configuration


class TranslateTextRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'resource': 'dict(str, object)',
        'text': 'str',
        'source_language': 'str',
        'target_language': 'str'
    }

    attribute_map = {
        'resource': 'resource',
        'text': 'text',
        'source_language': 'sourceLanguage',
        'target_language': 'targetLanguage'
    }

    def __init__(self, resource=None, text=None, source_language=None, target_language=None, local_vars_configuration=None):  # noqa: E501
        """TranslateTextRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._resource = None
        self._text = None
        self._source_language = None
        self._target_language = None
        self.discriminator = None

        if resource is not None:
            self.resource = resource
        self.text = text
        if source_language is not None:
            self.source_language = source_language
        self.target_language = target_language

    @property
    def resource(self):
        """Gets the resource of this TranslateTextRequest.  # noqa: E501

        Use this field to associate metadata for the translate request.  # noqa: E501

        :return: The resource of this TranslateTextRequest.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._resource

    @resource.setter
    def resource(self, resource):
        """Sets the resource of this TranslateTextRequest.

        Use this field to associate metadata for the translate request.  # noqa: E501

        :param resource: The resource of this TranslateTextRequest.  # noqa: E501
        :type: dict(str, object)
        """

        self._resource = resource

    @property
    def text(self):
        """Gets the text of this TranslateTextRequest.  # noqa: E501


        :return: The text of this TranslateTextRequest.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this TranslateTextRequest.


        :param text: The text of this TranslateTextRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and text is None:  # noqa: E501
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def source_language(self):
        """Gets the source_language of this TranslateTextRequest.  # noqa: E501


        :return: The source_language of this TranslateTextRequest.  # noqa: E501
        :rtype: str
        """
        return self._source_language

    @source_language.setter
    def source_language(self, source_language):
        """Sets the source_language of this TranslateTextRequest.


        :param source_language: The source_language of this TranslateTextRequest.  # noqa: E501
        :type: str
        """

        self._source_language = source_language

    @property
    def target_language(self):
        """Gets the target_language of this TranslateTextRequest.  # noqa: E501


        :return: The target_language of this TranslateTextRequest.  # noqa: E501
        :rtype: str
        """
        return self._target_language

    @target_language.setter
    def target_language(self, target_language):
        """Sets the target_language of this TranslateTextRequest.


        :param target_language: The target_language of this TranslateTextRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and target_language is None:  # noqa: E501
            raise ValueError("Invalid value for `target_language`, must not be `None`")  # noqa: E501

        self._target_language = target_language

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranslateTextRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TranslateTextRequest):
            return True

        return self.to_dict() != other.to_dict()
