# coding: utf-8

"""
    Dalet Metadata Analysis API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.1.0
    Contact: cortexsupport@dalet.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from metadataanalysis_client.configuration import Configuration


class TranslateCaptionsResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ttml_file': 'Locator',
        'text_file': 'Locator'
    }

    attribute_map = {
        'ttml_file': 'ttmlFile',
        'text_file': 'textFile'
    }

    def __init__(self, ttml_file=None, text_file=None, local_vars_configuration=None):  # noqa: E501
        """TranslateCaptionsResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ttml_file = None
        self._text_file = None
        self.discriminator = None

        self.ttml_file = ttml_file
        if text_file is not None:
            self.text_file = text_file

    @property
    def ttml_file(self):
        """Gets the ttml_file of this TranslateCaptionsResponse.  # noqa: E501


        :return: The ttml_file of this TranslateCaptionsResponse.  # noqa: E501
        :rtype: Locator
        """
        return self._ttml_file

    @ttml_file.setter
    def ttml_file(self, ttml_file):
        """Sets the ttml_file of this TranslateCaptionsResponse.


        :param ttml_file: The ttml_file of this TranslateCaptionsResponse.  # noqa: E501
        :type: Locator
        """
        if self.local_vars_configuration.client_side_validation and ttml_file is None:  # noqa: E501
            raise ValueError("Invalid value for `ttml_file`, must not be `None`")  # noqa: E501

        self._ttml_file = ttml_file

    @property
    def text_file(self):
        """Gets the text_file of this TranslateCaptionsResponse.  # noqa: E501


        :return: The text_file of this TranslateCaptionsResponse.  # noqa: E501
        :rtype: Locator
        """
        return self._text_file

    @text_file.setter
    def text_file(self, text_file):
        """Sets the text_file of this TranslateCaptionsResponse.


        :param text_file: The text_file of this TranslateCaptionsResponse.  # noqa: E501
        :type: Locator
        """

        self._text_file = text_file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranslateCaptionsResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TranslateCaptionsResponse):
            return True

        return self.to_dict() != other.to_dict()
